Add konf
canonical/specs-v1.canonical.com pull request #31
Opened 2022-03-24 15:07 UTC by andesol

## Done 

- Add `site.yml` file

## Issue

Fixes #18

2022-03-28 10:21 UTC, goulinkh requested changes

2022-03-28 10:21 UTC, goulinkh commented on konf/site.yml
> +  - name: GOOGLE_PRIVATE_KEY_ID
This has to be the same name as [here](https://github.com/canonical-web-and-design/specs.canonical.com/blob/main/webapp/spreasheet.py#L10):
```py
os.getenv("PRIVATE_KEY_ID")
```

2022-03-28 10:21 UTC, goulinkh commented on konf/site.yml
> +  - name: GOOGLE_PRIVATE_KEY
Same here

2022-03-28 11:15 UTC, andesol commented
Ops, guess I forgot my own naming conventions...

2022-03-29 08:34 UTC, tbille commented on konf/site.yml
> +    value: https://f51f18282e7d44bebe6cc268ba96f7a2@sentry.is.canonical.com//49
```suggestion
    value: https://e38013698989400884cce7bd9d862af3@sentry.is.canonical.com//51
```

I just created a project for [specs.canonical.com on sentry](https://sentry.is.canonical.com/canonical/specs-canonical-com/). You can use this variable instead :)

2022-03-29 08:34 UTC, tbille approved these changes
One small change and feel free to merge.

2022-03-29 14:06 UTC, merged