WIP | abstract spec preview
canonical/specs-v1.canonical.com pull request #90
Opened 2022-08-09 15:20 UTC by Dampolo03

## Done
- Added abstract spec preview on click of a spec card title.
- Added new endpoint `/spec/<string:document_id>` that returns the document's html, metadata and respective document url.

## QA
- As we don't have access to docs, you need to login using the app credentials - `credentials.json` (this file can be shared with you).
- Start the project - `dotrun`.
- Login to your Google account.
- Click a spec card title.
- Ensure the abstract preview is displayed.
- Click the close button and ensure the preview is closed.
- Click another card title and ensure the preview is updated.
- Ensure the preview can be focused on with the `Tab` key.
- Ensure that the user is redirected to the respective document on click of the 'Open in Google Docs' button.

2022-08-09 15:20 UTC, webteam-app commented
Demo starting at https://specs-canonical-com-90.demos.haus

2022-08-09 15:37 UTC, goulinkh requested changes
Great work Dami :tada: 
I left some comments to insure that we follow the same convention and maintain clean structure :)

2022-08-09 15:37 UTC, goulinkh commented on client/Loader.tsx
> +const Loader = () => {
This is unnecessary as it's already implemented: https://canonical.github.io/react-components/?path=/docs/loader--default-story

2022-08-09 15:37 UTC, goulinkh commented on client/SpecCard.tsx
> +  const [obtainedData, setObtainedData] = useState<ObtainedData>({
Maybe something like `specDetails` is more specific in this case?

2022-08-09 15:37 UTC, goulinkh commented on client/SpecCard.tsx
> +      console.log(obtainedData);
A forgotten comment :)

2022-08-09 15:37 UTC, goulinkh commented on client/SpecCard.tsx
> +    const obtainedData = await response.json();
these should be surrounded by a try/catch if you want to catch errors of type: server unreachable and response not of JSON format

2022-08-09 15:37 UTC, goulinkh commented on client/SpecCard.tsx
> +          lastEdited={lastEdited}
I think moving the loading part (fetch from server) into the specDetails component should make this more readable also don't hesitate to use custom hooks for breaking the component `SpecDetailsProps` into smaller pieces

2022-08-09 15:37 UTC, goulinkh commented on client/styles.scss
> +$spec-preview-backdrop: #00000040;
rgba?

2022-08-09 15:37 UTC, goulinkh commented on client/styles.scss
> +
this is already implemented: https://canonical.github.io/react-components/?path=/docs/switch--default-story

2022-08-10 09:44 UTC, andesol commented on client/SpecsDetails.tsx
> +                {/* The get notifications feature isn't functional yet */}
I think we shouldn't include this in the UI if it's not functional. Thoughts, @goulinkh ?

2022-08-10 10:09 UTC, andesol commented
If you Tab several times the focus goes to the background. The focus should be trapped in the preview section (there must be some react library that makes this "easy").

2022-08-10 10:40 UTC, Dampolo03 commented
> If you `tab` several times the focus goes to the background. Ideally, the focus should be trapped in the preview section (there must be some react library that makes this "easy").

@andesol alright, will look into this.

2022-08-10 11:13 UTC, Dampolo03 commented on client/Loader.tsx
> +const Loader = () => {
Done

2022-08-10 11:13 UTC, Dampolo03 commented on client/SpecCard.tsx
> +  const [obtainedData, setObtainedData] = useState<ObtainedData>({
Done

2022-08-10 11:14 UTC, Dampolo03 commented on client/SpecCard.tsx
> +      console.log(obtainedData);
Removed.

2022-08-10 11:14 UTC, Dampolo03 commented on client/SpecCard.tsx
> +    const obtainedData = await response.json();
Done.

2022-08-10 11:14 UTC, Dampolo03 commented on client/SpecCard.tsx
> +          lastEdited={lastEdited}
Done.

2022-08-10 11:14 UTC, Dampolo03 commented on client/styles.scss
> +$spec-preview-backdrop: #00000040;
Changed.

2022-08-10 11:14 UTC, Dampolo03 commented on client/styles.scss
> +
Done.

2022-08-10 12:51 UTC, Dampolo03 commented
> If you `tab` several times the focus goes to the background. Ideally, the focus should be trapped in the preview section (there must be some react library that makes this "easy").

@andesol implemented.

2022-08-10 13:09 UTC, goulinkh submitted a review, later dismissed

2022-08-10 13:09 UTC, goulinkh commented on client/utils.ts
> +    "a[href], button:not([disabled]), textarea, input, select"
`onKeyDown` with a specific list selectors isn't ideal as it's redefining the list of focusable elements and implementing the focus functionality manually as part of the app.
After doing some search I've found this https://robinvdvleuten.nl/blog/trap-focus-in-a-react-component/ which mentions this library https://www.npmjs.com/package/focus-trap

2022-08-10 14:20 UTC, Dampolo03 commented on client/utils.ts
> +    "a[href], button:not([disabled]), textarea, input, select"
Done.

2022-08-11 08:25 UTC, andesol commented on client/SpecsDetails.tsx
> +                    role="button"
I think I'm the source of this confusion because I suggested a `role=button` in the last PR, but I was referring to the one that opened the preview. This one is a standard link, so no need for a `role` attribute

2022-08-11 08:33 UTC, andesol commented on webapp/app.py
> +from flask_restful import Resource, Api
I wonder if we really need flask_restful. I think in this case standard flask would be enough without any extra dependency. 

```
@app.route("/<document_id>")
def get_document(document_id):
   ...
   ...
    return jsonify(payload)

2022-08-11 09:06 UTC, andesol commented
Looking really good! Just two things that didn't work for me:

- Seems like cards somehow are not "tabbable", so when you hit "skip to main content" it doesn't let you go through the cards.
- When you click outside the preview it doesn't close

2022-08-11 13:45 UTC, Dampolo03 commented
> Looking really good! Just two things that didn't work for me:
> 
> * Seems like cards somehow are not "tabbable", so when you hit "skip to main content" it doesn't let you go through the cards.
> * When you click outside the preview it doesn't close

@andesol Done. Please confirm.

2022-08-11 15:33 UTC, andesol commented
Sorry, when I said that cards were not "tabbable", I meant that a we should be able to go through the focusable elements of the cards and be able to open the preview. So the focus really shouldn't be in the card itself, but in the link. Sorry f that was confusing. 

Other than that, LGTM!

PS: 
![image](https://user-images.githubusercontent.com/20623084/184171642-6627e946-9f8e-4477-9764-f9940c0b62d1.png)
I think this was solved in [this PR](https://github.com/canonical/specs.canonical.com/pull/89), so you may need to update your branch?

2022-08-12 10:06 UTC, andesol commented
LGTM! Nice work

Only two final comments: 
- The "Open in Google Docs" button doesn't seem  reachable with the keyboard. We can address it in another PR, no need to do it now.
- I still see the label too big (see image above). Hopefully it's just a matter of updating the branch

2022-08-12 10:16 UTC, goulinkh commented
This PR can't be merged as it will break the production, we need to ask IS to give some access to the used google service account, once we have access. We can merge this safely.

2022-08-12 10:32 UTC, Dampolo03 commented
> LGTM! Nice work
> 
> Only two final comments:
> 
> * The "Open in Google Docs" button doesn't seem  reachable with the keyboard. We can address it in another PR, no need to do it now.
> * I still see the label too big (see image above). Hopefully it's just a matter of updating the branch

@andesol Please re-confirm.

2022-08-12 10:32 UTC, Dampolo03 commented
> This PR can't be merged as it will break the production, we need to ask IS to give some access to the used google service account, once we have access. We can merge this safely.

Sounds good.

2022-08-15 13:01 UTC, sparkiegeek commented
> Added new endpoint /spec/<string:document_id> that returns the document's html, metadata and respective document url.

`/spec/<string:...>` is already an existing endpoint used by users of specs.canonical.com, please don't hijack it for this

2022-08-15 13:46 UTC, sparkiegeek requested changes

2022-08-15 13:46 UTC, sparkiegeek commented on webapp/app.py
> -        flask.abort(404)
Please use a different URL for the mini-spec

2022-08-15 14:26 UTC, Dampolo03 commented on webapp/app.py
> -        flask.abort(404)
> Please use a different URL for the mini-spec

Thanks, will look into this.

2022-08-22 09:58 UTC, marinacastejon commented
Hi @Dampolo03 
This is not a big deal, but ideally the style should follow the google docs. It is not exactly the same (although quite close). If this is not too complex, I'd suggest fixing it. An example:
- Preview in specs.canonical.com
<img width="288" alt="image" src="https://user-images.githubusercontent.com/89836430/185893912-74da9d45-02aa-4a55-b8fb-311bb162bd02.png">
- Google doc
<img width="279" alt="image" src="https://user-images.githubusercontent.com/89836430/185894034-d73723bc-2863-4ad3-b759-e917226b23c9.png">

Other than that, looks good to me, thanks!

@andesol thanks for paying attention to the keyboard navigation and the accessibility of this page :) Btw I guess then you can close[ this old issue](https://app.zenhub.com/workspaces/-workplace-engineering-tribe-609110e401afd80010276c3b/issues/canonical/specs.canonical.com/58)?

2022-08-24 16:06 UTC, andesol commented
We have to remember to change the part of the code that uses oauth to use the service account instead (once we get the access to Drive)

2022-10-06 08:02 UTC, andesol commented on webapp/spec.py
> +        service_account_info = {
We are using this dict in `spreadsheet.py` too (to access the sheet with the list of specs with the same service account). I'd suggest extracting this to a common module. Maybe just a `settings.py` could be a simple solution?

2022-10-06 08:03 UTC, andesol reviewed
It works fine, I think we have everything now. Just left a minor comment.

2022-10-06 08:31 UTC, Dampolo03 commented on webapp/spec.py
> +        service_account_info = {
@andesol Done.

2022-10-06 09:47 UTC, andesol requested changes

2022-10-06 09:47 UTC, andesol commented on settings.py
> +import os
I'd suggest moving this into the `webapp` folder so all python files are together

2022-10-06 09:47 UTC, andesol commented on webapp/spec.py
> +            service_account_info, scopes=scopes
No need to redefine this variable? 
```suggestion
        credentials = service_account.Credentials.from_service_account_info(
            SERVICE_ACCOUNT_INFO, scopes=scopes
```

2022-10-06 11:02 UTC, andesol approved these changes

2022-10-06 11:10 UTC, merged